Add core code but introduce selector error
Code found on the Page.type() page in puppeteer documentation.
Currently having an error when selecting the text box:

Error: failed to find element matching selector "#words"
    at ElementHandle.$eval